/** Shared UI class strings — keep in sync with app/globals.css @layer components */

export const ui = {
  shell: "app-shell",
  header: "app-header",
  headerInner: "app-header-inner",
  brand: "app-brand",
  brandMark: "app-brand-mark",
  nav: "app-nav",
  navLink: "app-nav-link",
  navLinkActive: "app-nav-link-active",
  userChip: "app-user-chip",
  userName: "app-user-name",
  main: "app-main",
  pageHeader: "page-header",
  pageTitle: "page-header-title",
  pageDesc: "page-header-desc",
  card: "app-card",
  cardVisible: "app-card app-card-visible",
  cardPadded: "app-card app-card-padded",
  cardMuted: "app-card app-card-muted",
  cardAccent: "app-card app-card-accent",
  alertWarning: "app-alert app-alert-warning",
  alertInfo: "app-alert app-alert-info",
  alertDanger: "app-alert app-alert-danger",
  alertSuccess: "app-alert app-alert-success",
  btn: "btn",
  btnPrimary: "btn btn-primary",
  btnPrimarySm: "btn btn-primary btn-sm",
  btnPrimaryXs: "btn btn-primary btn-xs",
  btnPrimaryFull: "btn btn-primary w-full",
  btnSecondary: "btn btn-secondary",
  btnSecondarySm: "btn btn-secondary btn-sm",
  btnAccent: "btn btn-accent",
  btnGhost: "btn btn-ghost btn-sm",
  input: "input",
  label: "label",
  badgeSuccess: "badge badge-success",
  badgeWarning: "badge badge-warning",
  badgeDanger: "badge badge-danger",
  badgeInfo: "badge badge-info",
  badgeNeutral: "badge badge-neutral",
  badgeBrand: "badge badge-brand",
  orderRow: "order-row",
  orderRowHighlight: "order-row order-row-highlight",
  emptyState: "empty-state",
  filterPill: "filter-pill",
  filterPillActive: "filter-pill filter-pill-active",
  dataTable: "data-table",
  linkBack: "text-sm font-medium text-brand-700 underline decoration-brand-300 underline-offset-2 hover:text-brand-900",
} as const;
